# Stage 1: Build
FROM node:18-alpine AS build

# Accept build arguments for environment variables
ARG VITE_API_URL
ARG VITE_JWT_AUDIENCE
ARG VITE_JWT_ISSUER
ARG VITE_JWT_EXPIRY_DAYS
ARG VITE_BYPASS_AUTH
ARG VITE_APP_NAME
ARG VITE_APP_TITLE
ARG VITE_DEFAULT_LANGUAGE
ARG VITE_ENABLE_TELEMETRY
ARG VITE_ENABLE_GEOLOCATION
ARG VITE_ENABLE_VOICE_INPUT
ARG VITE_ENABLE_TTS
ARG VITE_MAX_RECORDING_DURATION
ARG VITE_AUDIO_SERVICE_TYPE
ARG VITE_DEBUG_MODE
ARG VITE_USE_MOCK_DATA
ARG VITE_TELEMETRY_HOST
ARG VITE_TELEMETRY_KEY
ARG VITE_TELEMETRY_SECRET
ARG VITE_TELEMETRY_CHANNEL
ARG VITE_TELEMETRY_PRODUCT_ID
ARG VITE_TELEMETRY_PRODUCT_VERSION
ARG VITE_TELEMETRY_PRODUCT_PID
ARG VITE_DEFAULT_THEME
ARG VITE_ENABLE_ANIMATIONS
ARG VITE_SUPPORTED_LANGUAGES

# Set environment variables from build args
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_JWT_AUDIENCE=$VITE_JWT_AUDIENCE
ENV VITE_JWT_ISSUER=$VITE_JWT_ISSUER
ENV VITE_JWT_EXPIRY_DAYS=$VITE_JWT_EXPIRY_DAYS
ENV VITE_BYPASS_AUTH=$VITE_BYPASS_AUTH
ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_APP_TITLE=$VITE_APP_TITLE
ENV VITE_DEFAULT_LANGUAGE=$VITE_DEFAULT_LANGUAGE
ENV VITE_ENABLE_TELEMETRY=$VITE_ENABLE_TELEMETRY
ENV VITE_ENABLE_GEOLOCATION=$VITE_ENABLE_GEOLOCATION
ENV VITE_ENABLE_VOICE_INPUT=$VITE_ENABLE_VOICE_INPUT
ENV VITE_ENABLE_TTS=$VITE_ENABLE_TTS
ENV VITE_MAX_RECORDING_DURATION=$VITE_MAX_RECORDING_DURATION
ENV VITE_AUDIO_SERVICE_TYPE=$VITE_AUDIO_SERVICE_TYPE
ENV VITE_DEBUG_MODE=$VITE_DEBUG_MODE
ENV VITE_USE_MOCK_DATA=$VITE_USE_MOCK_DATA
ENV VITE_TELEMETRY_HOST=$VITE_TELEMETRY_HOST
ENV VITE_TELEMETRY_KEY=$VITE_TELEMETRY_KEY
ENV VITE_TELEMETRY_SECRET=$VITE_TELEMETRY_SECRET
ENV VITE_TELEMETRY_CHANNEL=$VITE_TELEMETRY_CHANNEL
ENV VITE_TELEMETRY_PRODUCT_ID=$VITE_TELEMETRY_PRODUCT_ID
ENV VITE_TELEMETRY_PRODUCT_VERSION=$VITE_TELEMETRY_PRODUCT_VERSION
ENV VITE_TELEMETRY_PRODUCT_PID=$VITE_TELEMETRY_PRODUCT_PID
ENV VITE_DEFAULT_THEME=$VITE_DEFAULT_THEME
ENV VITE_ENABLE_ANIMATIONS=$VITE_ENABLE_ANIMATIONS
ENV VITE_SUPPORTED_LANGUAGES=$VITE_SUPPORTED_LANGUAGES

WORKDIR /usr/local/app
COPY ./ /usr/local/app/
RUN npm install
RUN npm run build

# Stage 2: Serve
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /usr/local/app/dist .
# Add nginx config for SPA routing
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Start Nginx
CMD ["/bin/sh", "-c", "find /usr/share/nginx/html -type f -name '*.js' -exec sed -i \"s|__RUNTIME_VITE_API_URL__|${VITE_API_URL:-http://127.0.0.1:8000}|g\" {} + && nginx -g 'daemon off;'"]